chunk-GNV6WKGW.js:67 
 POST http://localhost:3000/api/login net::ERR_CONNECTION_REFUSED
(anónimo)	@	chunk-GNV6WKGW.js:67
(anónimo)	@	chunk-GNV6WKGW.js:67
runOutsideAngular	@	chunk-GNV6WKGW.js:66
doRequest	@	chunk-GNV6WKGW.js:67
(anónimo)	@	chunk-GNV6WKGW.js:67
_trySubscribe	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
lr	@	chunk-GNV6WKGW.js:65
subscribe	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
lr	@	chunk-GNV6WKGW.js:65
subscribe	@	chunk-GNV6WKGW.js:65
w	@	chunk-GNV6WKGW.js:65
m	@	chunk-GNV6WKGW.js:65
_next	@	chunk-GNV6WKGW.js:65
next	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
_trySubscribe	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
lr	@	chunk-GNV6WKGW.js:65
subscribe	@	chunk-GNV6WKGW.js:65
Eh	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
lr	@	chunk-GNV6WKGW.js:65
subscribe	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
lr	@	chunk-GNV6WKGW.js:65
subscribe	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
lr	@	chunk-GNV6WKGW.js:65
subscribe	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
(anónimo)	@	chunk-GNV6WKGW.js:65
lr	@	chunk-GNV6WKGW.js:65
subscribe	@	chunk-GNV6WKGW.js:65
onLogin	@	main-766E2RJS.js:37
(anónimo)	@	main-766E2RJS.js:37
im	@	chunk-GNV6WKGW.js:66
r	@	chunk-GNV6WKGW.js:66
(anónimo)	@	chunk-LNADORID.js:1